spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://localhost:8088"
  cache:
    type: redis
    redis:
      cache-null-values: false
      use-key-prefix: true
      time-to-live: 3000
  data:
    redis:
      host: redis-19160.c292.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 19160
      username: default
      password: UW1mVlhCWk5wakRxUkQ1MnZmdHlxYjVQZm9Ta0djYjk=
      havePassword: YES
    mongodb:
      host: localhost
      port: 27017
      database: notification-service
      username: admin
      password: Son191203